export default {
  SET_CURRENT_CITY: `SET_CURRENT_CITY`,
  GET_OFFERS_LIST: `GET_OFFERS_LIST`,
  SET_ACTIVE_OFFER: `SET_ACTIVE_OFFER`,
  SET_FOCUS_OFFER: `SET_FOCUS_OFFER`,
  REMOVE_FOCUS_OFFER: `REMOVE_FOCUS_OFFER`,
  GET_AVAILABLE_OFFERS: `GET_AVAILABLE_OFFERS`,
  TOGGLE_SORT_LIST: `TOGGLE_SORT_LIST`,
  SET_CURRENT_SORT: `SET_CURRENT_SORT`,
  GET_COORDINATES_WITHOUT_FOCUS: `GET_COORDINATES_WITHOUT_FOCUS`,
  SET_FOCUS_COORDINATE: `SET_FOCUS_COORDINATE`,
  REMOVE_FOCUS_COORDINATE: `REMOVE_FOCUS_COORDINATE`,
};
